n_layers: 5
dropout_prob: 0.5
temperature: 1.0
perturb_start_layer: 0
use_mse_loss: False
train_entity_mask: True
embedding_type: "medium"
no_gumbel: False
skip_marginalize: True
perturb_train_first_target_layer: 16
no_alpha_net: False
perturb_position: 0
n_scale_net_layers: 1
noise_type: "learnable"
loss_type: "kl"